// Code generated by codegen. DO NOT EDIT.
//	versions:
//		codegen	v0.0.0-SNAPSHOT-e142a79
//		go		go1.22.4
//	update:	1718121504
//	source: maids.proto

package main

import (
	"github.com/lazygophers/maids"
	"github.com/lazygophers/maids/internal/impl"
	"github.com/lazygophers/lrpc"
)

var app = lrpc.NewApp(&lrpc.Config{})

var Routes = []*lrpc.Route{ 
}
